name: Build README

on:
  push:
  workflow_dispatch:
    schedule:
    - cron:  '20 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.1
    - name: Set up Python 3.x
      uses: actions/setup-python@v2.1.1
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64' 
    
    - name: install requirements
      run: |
        python -m pip install -r requirements.txt
      
    - name: test_py
      run: |-
        python test.py
        cat README.md
    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
